"""
从 v4 报告中提取所有证据，生成统一的 evidence_index.jsonl。
"""
import json
from pathlib import Path

ANALYSES_DIR = Path(__file__).resolve().parents[1] / "analyses" / "demo"
OUTPUT = ANALYSES_DIR / "evidence_index.jsonl"

# 合成示例证据索引（用于测试和演示，不包含真实聊天内容）
EVIDENCE = [
    # E-20260601 系列
    {"evidence_id": "E-20260601-001", "date": "2026-06-01", "time": "23:14", "speaker": "B",
     "raw_quote": "别说了别说了 / 太尴尬了 / 算了算了",
     "context": "同事C 回到工位，B 担心话题被听到",
     "claim_tags": ["attachment-avoidant", "boundary-implicit", "persona-hard-rule"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是不想让办公室人际关系复杂化",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-002", "date": "2026-06-01", "time": "22:57", "speaker": "B",
     "raw_quote": "行吧不说了 / 我去洗澡了",
     "context": "A 在安抚 B 关于同事C的事，B 结束话题",
     "claim_tags": ["pattern-withdraw", "persona-hard-rule", "expression-nonliteral"],
     "confidence": "high", "counter_evidence": "在非情感话题上 B 也会主动延续对话",
     "alternative_explanation": "可能只是累了或话题自然结束",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-003", "date": "2026-06-01", "time": "15:38", "speaker": "B",
     "raw_quote": "[图片] 这个怎么弄",
     "context": "B 遇到技术问题主动求助",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "只是因为 A 恰好懂技术",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-004", "date": "2026-06-01", "time": "23:24", "speaker": "B",
     "raw_quote": "[表情] x10+ 刷屏",
     "context": "讨论办公室关系时 B 连续发表情",
     "claim_tags": ["persona-hard-rule", "expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是个人表达习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-005", "date": "2026-06-01", "time": "23:23", "speaker": "B",
     "raw_quote": "我比较小心",
     "context": "B 对办公室社交极度谨慎",
     "claim_tags": ["boundary-implicit", "persona-boundary"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是当前阶段不想公开",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-006", "date": "2026-06-01", "time": "23:14", "speaker": "A",
     "raw_quote": "没事的 / 别怕 / 放心好了",
     "context": "B 恐慌时 A 连续安抚",
     "claim_tags": ["persona-hard-rule", "pattern-approach", "conflict-repair"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是朋友间的正常安慰",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-007", "date": "2026-06-01", "time": "22:32", "speaker": "A",
     "raw_quote": "感觉前辈对同事C越来越不满了",
     "context": "A 分享办公室八卦，B 积极回应",
     "claim_tags": ["pattern-communication"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是普通朋友间的分享",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-008", "date": "2026-06-01", "time": "23:15", "speaker": "B",
     "raw_quote": "我信了",
     "context": "A 说'我又没做亏心事'，B 开玩笑回应",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是随口配合玩笑",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-009", "date": "2026-06-01", "time": "14:56", "speaker": "B",
     "raw_quote": "6",
     "context": "A 说奶茶忘拿了",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是个人数字表达习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-010", "date": "2026-06-01", "time": "22:31", "speaker": "B",
     "raw_quote": "嗯",
     "context": "询问情况",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是个人用语习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-011", "date": "2026-06-01", "time": "22:56", "speaker": "B",
     "raw_quote": "。。。。。。。。",
     "context": "讨论办公室关系",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是无意义的输入习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-012", "date": "2026-06-01", "time": "23:14", "speaker": "A",
     "raw_quote": "气氛突然安静了",
     "context": "同事C 回到工位后的尴尬氛围",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是夸张的日常表达",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-013", "date": "2026-06-01", "time": "22:32", "speaker": "A",
     "raw_quote": "感觉前辈对同事C越来越不满了",
     "context": "办公室冲突触发",
     "claim_tags": ["conflict-escalation"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是普通朋友间的分享",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260602 系列
    {"evidence_id": "E-20260602-001", "date": "2026-06-02", "time": "13:25", "speaker": "B",
     "raw_quote": "在吗！",
     "context": "B 主动联系 A",
     "claim_tags": ["pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是恰好有事找对方",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260603 系列
    {"evidence_id": "E-20260603-001", "date": "2026-06-03", "time": "22:06", "speaker": "B",
     "raw_quote": "你会修吗？ / 麻烦不？",
     "context": "B 求助修电脑",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "只是因为 A 恰好懂技术",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-002", "date": "2026-06-03", "time": "21:23", "speaker": "B",
     "raw_quote": "好难吃 / 好难吃 / [表情]",
     "context": "外卖不好吃，共同吐槽",
     "claim_tags": ["pattern-communication", "expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是食物确实不好吃",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-003", "date": "2026-06-03", "time": "22:07", "speaker": "B",
     "raw_quote": "我把那个旧的出了 / 卖掉了",
     "context": "B 卖旧物，自信谈价",
     "claim_tags": ["persona-identity"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是正常的二手交易",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-004", "date": "2026-06-03", "time": "22:06", "speaker": "A",
     "raw_quote": "可以啊 / 不麻烦",
     "context": "A 答应帮 B 修东西",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是朋友间的举手之劳",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-005", "date": "2026-06-03", "time": "22:13", "speaker": "A",
     "raw_quote": "这种小事我自己就能搞定",
     "context": "A 对技术能力的自信",
     "claim_tags": ["persona-identity"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是随口一说",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-006", "date": "2026-06-03", "time": "22:17", "speaker": "B",
     "raw_quote": "我这人真的[尴尬]很喜欢断舍离",
     "context": "B 自嘲卖东西",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是自嘲式的社交表达",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-007", "date": "2026-06-03", "time": "22:54", "speaker": "B",
     "raw_quote": "这拍的也太好看了吧",
     "context": "看到漂亮照片",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是看到好看照片的正常反应",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260604 系列
    {"evidence_id": "E-20260604-001", "date": "2026-06-04", "time": "01:01", "speaker": "B",
     "raw_quote": "好了不聊了，1点了",
     "context": "A 分享项目后 B 结束对话",
     "claim_tags": ["pattern-withdraw", "persona-hard-rule"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是累了",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-002", "date": "2026-06-04", "time": "00:56", "speaker": "B",
     "raw_quote": "嗯嗯",
     "context": "A 说'慢慢来吧。反正我在呢'后 B 简短回应",
     "claim_tags": ["attachment-avoidant", "pattern-withdraw"],
     "confidence": "medium", "counter_evidence": "B 在某些时刻也会主动分享",
     "alternative_explanation": "可能不知道如何回应",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-003", "date": "2026-06-04", "time": "00:55", "speaker": "B",
     "raw_quote": "但我确实是不太会表达 / 。。。。。",
     "context": "A 分享分析结果后 B 自我标签化",
     "claim_tags": ["attachment-avoidant", "persona-decision"],
     "confidence": "medium", "counter_evidence": "自我标签可能不准确",
     "alternative_explanation": "可能只是随口一说",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-004", "date": "2026-06-04", "time": "13:14", "speaker": "A",
     "raw_quote": "算了顺手清一下吧 / 都拆了",
     "context": "A 主动多做事",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是顺手帮忙",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-005", "date": "2026-06-04", "time": "00:56", "speaker": "A",
     "raw_quote": "就算我会乱想，忙起来就好了",
     "context": "A 描述自我调节方式",
     "claim_tags": ["persona-hard-rule", "persona-decision", "attachment-secure"],
     "confidence": "high", "counter_evidence": "可能只是表面适应",
     "alternative_explanation": "可能是因为忙，而非心态转变",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-006", "date": "2026-06-04", "time": "00:15", "speaker": "A",
     "raw_quote": "叫示例项目 / 。。。有点羞耻",
     "context": "A 分享示例项目",
     "claim_tags": ["persona-hard-rule", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是谦虚",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-007", "date": "2026-06-04", "time": "00:15", "speaker": "A",
     "raw_quote": "有点不好意思",
     "context": "A 分享作品时的羞耻感",
     "claim_tags": ["persona-identity"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是谦虚的社交惯用语",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-008", "date": "2026-06-04", "time": "00:59", "speaker": "A",
     "raw_quote": "好像心态也有了一些转变 / 要先做自己呢",
     "context": "A 描述心态变化",
     "claim_tags": ["persona-decision", "attachment-secure"],
     "confidence": "medium", "counter_evidence": "可能只是成熟了",
     "alternative_explanation": "可能是因为忙",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-009", "date": "2026-06-04", "time": "00:47", "speaker": "B",
     "raw_quote": "[脸红]",
     "context": "A 说'我发截图给你看'",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是表情包使用习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-010", "date": "2026-06-04", "time": "00:42", "speaker": "B",
     "raw_quote": "行吧行吧，你凶我",
     "context": "A 表达被冷落的感受后 B 的反应",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是玩笑式的回应",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-011", "date": "2026-06-04", "time": "00:44", "speaker": "A",
     "raw_quote": "我发截图给你看",
     "context": "A 分享分析结果",
     "claim_tags": ["expression-nonliteral", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是分享有趣内容的社交行为",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-012", "date": "2026-06-04", "time": "13:05", "speaker": "A",
     "raw_quote": "好难弄！！！！",
     "context": "帮 B 修东西",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是操作确实困难",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-013", "date": "2026-06-04", "time": "18:08", "speaker": "A",
     "raw_quote": "想多了",
     "context": "B 问 A 会不会介意叫朋友一起吃饭",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是朋友间的玩笑反驳",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-014", "date": "2026-06-04", "time": "00:36", "speaker": "A",
     "raw_quote": "和你说这个不是给你压力，也不是邀功",
     "context": "A 分享项目灵感来源时的预防性解释",
     "claim_tags": ["expression-nonliteral", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是正常的分享动机",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-015", "date": "2026-06-04", "time": "00:52", "speaker": "A",
     "raw_quote": "你看看就好，就是随便玩玩",
     "context": "A 分享分析结果时降低期待",
     "claim_tags": ["expression-nonliteral", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是不想给对方压力",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260605 系列
    {"evidence_id": "E-20260605-001", "date": "2026-06-05", "time": "12:13", "speaker": "B",
     "raw_quote": "你咋知道[尴尬]还有这个功能",
     "context": "B 求助售后问题",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是真的不知道",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260605-002", "date": "2026-06-05", "time": "12:34", "speaker": "A",
     "raw_quote": "拉群是为了给你撑场面嘛[翻白眼]",
     "context": "B 建议拉群",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是开玩笑的社交表达",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # 从 v3 报告保留的关键证据
    {"evidence_id": "E-20260517-001", "date": "2026-05-17", "time": "03:09", "speaker": "B",
     "raw_quote": "先低调一点别声张",
     "context": "A 表白后 B 的回应",
     "claim_tags": ["attachment-avoidant", "boundary-implicit"],
     "confidence": "high", "counter_evidence": "可能是当前阶段不想公开",
     "alternative_explanation": "可能只是谨慎，而非回避",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260528-001", "date": "2026-05-28", "time": "01:22", "speaker": "A",
     "raw_quote": "学姐出去没找到学长",
     "context": "答辩后疏离期开始",
     "claim_tags": ["turning-point"],
     "confidence": "medium", "counter_evidence": None,
     "alternative_explanation": "可能只是正常的信息传递",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20241101-001", "date": "2024-11-01", "time": None, "speaker": "B",
     "raw_quote": "我在紧张地玩",
     "context": "早期 B 表达焦虑",
     "claim_tags": ["attachment-anxious", "expression-emotional"],
     "confidence": "medium", "counter_evidence": None,
     "alternative_explanation": "可能只是随口一说",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
]


def main():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        for ev in EVIDENCE:
            f.write(json.dumps(ev, ensure_ascii=False) + "\n")
    print(f"Wrote {len(EVIDENCE)} evidence records to {OUTPUT}")


if __name__ == "__main__":
    main()
