"""
从 v4 报告中提取所有证据，生成统一的 evidence_index.jsonl。
"""
import json
from pathlib import Path

ANALYSES_DIR = Path(__file__).resolve().parents[1] / "analyses" / "zy-tf"
OUTPUT = ANALYSES_DIR / "evidence_index.jsonl"

# 手工整理的证据索引（从 v4 报告中提取）
EVIDENCE = [
    # E-20260601 系列
    {"evidence_id": "E-20260601-001", "date": "2026-06-01", "time": "23:14", "speaker": "Tf",
     "raw_quote": "救命 / 救命啊 / 救命 / 救命 / 。。。。。。。。 / 太恐怖了 / 太恐怖了",
     "context": "云鹏回到实验室，Tf 担心关系暴露",
     "claim_tags": ["attachment-avoidant", "boundary-implicit", "persona-hard-rule"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是不想让实验室人际关系复杂化",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-002", "date": "2026-06-01", "time": "22:57", "speaker": "Tf",
     "raw_quote": "好的，不管了 / 吹头发",
     "context": "Zy 在安抚 Tf 关于云鹏的事，Tf 结束话题",
     "claim_tags": ["pattern-withdraw", "persona-hard-rule", "expression-nonliteral"],
     "confidence": "high", "counter_evidence": "在非情感话题上 Tf 也会主动延续对话",
     "alternative_explanation": "可能只是累了或话题自然结束",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-003", "date": "2026-06-01", "time": "15:38", "speaker": "Tf",
     "raw_quote": "[图片] help",
     "context": "Tf 遇到技术问题主动求助",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "只是因为 Zy 恰好懂技术",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-004", "date": "2026-06-01", "time": "23:24", "speaker": "Tf",
     "raw_quote": "[表情] x10+ 刷屏",
     "context": "讨论实验室关系时 Tf 连续发表情",
     "claim_tags": ["persona-hard-rule", "expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是个人表达习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-005", "date": "2026-06-01", "time": "23:23", "speaker": "Tf",
     "raw_quote": "谨慎小心",
     "context": "Tf 对实验室社交极度谨慎",
     "claim_tags": ["boundary-implicit", "persona-boundary"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是当前阶段不想公开",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-006", "date": "2026-06-01", "time": "23:14", "speaker": "Zy",
     "raw_quote": "不救命 / 别怕 / 你放心 / 云鹏也不敢怎么样你",
     "context": "Tf 恐慌时 Zy 连续安抚",
     "claim_tags": ["persona-hard-rule", "pattern-approach", "conflict-repair"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是朋友间的正常安慰",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-007", "date": "2026-06-01", "time": "22:32", "speaker": "Zy",
     "raw_quote": "感觉师兄对云鹏越想越气",
     "context": "Zy 分享实验室八卦，Tf 积极回应",
     "claim_tags": ["pattern-communication"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是普通朋友间的分享",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-008", "date": "2026-06-01", "time": "23:15", "speaker": "Tf",
     "raw_quote": "我做了",
     "context": "Zy 说'我又没有做亏心事'，Tf 开玩笑回应",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是随口配合玩笑",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-009", "date": "2026-06-01", "time": "14:56", "speaker": "Tf",
     "raw_quote": "6",
     "context": "Zy 说荔枝冰奶忘拿了",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是个人数字表达习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-010", "date": "2026-06-01", "time": "22:31", "speaker": "Tf",
     "raw_quote": "莫",
     "context": "询问情况",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是方言或个人用语习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-011", "date": "2026-06-01", "time": "22:56", "speaker": "Tf",
     "raw_quote": "。。。。。。。。",
     "context": "讨论实验室关系",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是无意义的输入习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-012", "date": "2026-06-01", "time": "23:14", "speaker": "Zy",
     "raw_quote": "死一般的寂静",
     "context": "云鹏回到实验室后的尴尬氛围",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是夸张的日常表达",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260601-013", "date": "2026-06-01", "time": "22:32", "speaker": "Zy",
     "raw_quote": "感觉师兄对云鹏越想越气",
     "context": "实验室冲突触发",
     "claim_tags": ["conflict-escalation"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是普通朋友间的分享",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260602 系列
    {"evidence_id": "E-20260602-001", "date": "2026-06-02", "time": "13:25", "speaker": "Tf",
     "raw_quote": "醒了吗！",
     "context": "Tf 主动联系 Zy",
     "claim_tags": ["pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是恰好有事找对方",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260603 系列
    {"evidence_id": "E-20260603-001", "date": "2026-06-03", "time": "22:06", "speaker": "Tf",
     "raw_quote": "你会拆吗？ / 麻烦不？",
     "context": "Tf 求助拆电脑",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "只是因为 Zy 恰好懂技术",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-002", "date": "2026-06-03", "time": "21:23", "speaker": "Tf",
     "raw_quote": "难吃 / 难吃 / 难吃 / [表情]",
     "context": "麻辣烫后肚子不舒服，共同吐槽",
     "claim_tags": ["pattern-communication", "expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是食物确实不好吃",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-003", "date": "2026-06-03", "time": "22:07", "speaker": "Tf",
     "raw_quote": "我把这个电脑转了 / 出了",
     "context": "Tf 卖电脑，自信谈价",
     "claim_tags": ["persona-identity"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是正常的二手交易",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-004", "date": "2026-06-03", "time": "22:06", "speaker": "Zy",
     "raw_quote": "会啊 / 不麻烦",
     "context": "Zy 答应帮 Tf 拆电脑",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是朋友间的举手之劳",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-005", "date": "2026-06-03", "time": "22:13", "speaker": "Zy",
     "raw_quote": "包有的啊我自己会给电脑清灰啊",
     "context": "Zy 对技术能力的自信",
     "claim_tags": ["persona-identity"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是随口一说",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-006", "date": "2026-06-03", "time": "22:17", "speaker": "Tf",
     "raw_quote": "我这人真的[尴尬]很喜欢断舍离",
     "context": "Tf 自嘲卖东西",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是自嘲式的社交表达",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260603-007", "date": "2026-06-03", "time": "22:54", "speaker": "Tf",
     "raw_quote": "bushi这咋拍出来的",
     "context": "看到漂亮照片",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是看到好看照片的正常反应",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260604 系列
    {"evidence_id": "E-20260604-001", "date": "2026-06-04", "time": "01:01", "speaker": "Tf",
     "raw_quote": "好，收，1点了",
     "context": "Zy 分享 BondLens 后 Tf 结束对话",
     "claim_tags": ["pattern-withdraw", "persona-hard-rule"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是累了",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-002", "date": "2026-06-04", "time": "00:56", "speaker": "Tf",
     "raw_quote": "嗯嗯",
     "context": "Zy 说'慢慢来吧。反正我在呢'后 Tf 简短回应",
     "claim_tags": ["attachment-avoidant", "pattern-withdraw"],
     "confidence": "medium", "counter_evidence": "Tf 在某些时刻也会主动分享",
     "alternative_explanation": "可能不知道如何回应",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-003", "date": "2026-06-04", "time": "00:55", "speaker": "Tf",
     "raw_quote": "但我确实是回避型 / 。。。。。",
     "context": "Zy 分享 BondLens 分析结果后 Tf 自我标签化",
     "claim_tags": ["attachment-avoidant", "persona-decision"],
     "confidence": "medium", "counter_evidence": "自我标签可能不准确",
     "alternative_explanation": "可能只是随口一说",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-004", "date": "2026-06-04", "time": "13:14", "speaker": "Zy",
     "raw_quote": "算了清一下吧 / 拆都拆了",
     "context": "Zy 主动多做清灰",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是顺手帮忙",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-005", "date": "2026-06-04", "time": "00:56", "speaker": "Zy",
     "raw_quote": "就算我会乱想，干干活打打游戏就好了",
     "context": "Zy 描述自我调节方式",
     "claim_tags": ["persona-hard-rule", "persona-decision", "attachment-secure"],
     "confidence": "high", "counter_evidence": "可能只是表面适应",
     "alternative_explanation": "可能是因为忙，而非心态转变",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-006", "date": "2026-06-04", "time": "00:15", "speaker": "Zy",
     "raw_quote": "叫bondlens / 。。。有点羞耻",
     "context": "Zy 分享 BondLens 项目",
     "claim_tags": ["persona-hard-rule", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是谦虚",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-007", "date": "2026-06-04", "time": "00:15", "speaker": "Zy",
     "raw_quote": "有点羞耻",
     "context": "Zy 分享作品时的羞耻感",
     "claim_tags": ["persona-identity"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是谦虚的社交惯用语",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-008", "date": "2026-06-04", "time": "00:59", "speaker": "Zy",
     "raw_quote": "好像心态也有一些转变 / 好像是要先做自己呢",
     "context": "Zy 描述心态变化",
     "claim_tags": ["persona-decision", "attachment-secure"],
     "confidence": "medium", "counter_evidence": "可能只是成熟了",
     "alternative_explanation": "可能是因为忙",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-009", "date": "2026-06-04", "time": "00:47", "speaker": "Tf",
     "raw_quote": "[脸红]",
     "context": "Zy 说'我远程给你看截图'",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是表情包使用习惯",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-010", "date": "2026-06-04", "time": "00:42", "speaker": "Tf",
     "raw_quote": "额。。救，快对我发火吧",
     "context": "Zy 表达被冷落的感受后 Tf 的反应",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是玩笑式的回应",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-011", "date": "2026-06-04", "time": "00:44", "speaker": "Zy",
     "raw_quote": "我远程给你看截图",
     "context": "Zy 羞耻地分享 BondLens 分析结果",
     "claim_tags": ["expression-nonliteral", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是分享有趣内容的社交行为",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-012", "date": "2026-06-04", "time": "13:05", "speaker": "Zy",
     "raw_quote": "好难拆！！！！",
     "context": "帮 Tf 拆电脑",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是技术操作确实困难",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-013", "date": "2026-06-04", "time": "18:08", "speaker": "Zy",
     "raw_quote": "发癫呢",
     "context": "Tf 问 Zy 会不会生气叫杭杭一起吃饭",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是朋友间的玩笑反驳",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-014", "date": "2026-06-04", "time": "00:36", "speaker": "Zy",
     "raw_quote": "和你说这个不是压力你，也不是说我当时怎么怎么样，也不是说我为你做了什么",
     "context": "Zy 分享 BondLens 灵感来源时的预防性解释",
     "claim_tags": ["expression-nonliteral", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是正常的分享动机",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260604-015", "date": "2026-06-04", "time": "00:52", "speaker": "Zy",
     "raw_quote": "你看看就好，反正也就是玩一玩嗷。我也没有要你干嘛",
     "context": "Zy 分享 BondLens 分析结果时降低期待",
     "claim_tags": ["expression-nonliteral", "persona-expression"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是不想给对方压力",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # E-20260605 系列
    {"evidence_id": "E-20260605-001", "date": "2026-06-05", "time": "12:13", "speaker": "Tf",
     "raw_quote": "你咋知道[尴尬]英伟达还有app",
     "context": "Tf 求助售后问题",
     "claim_tags": ["persona-hard-rule", "pattern-approach"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是真的不知道",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260605-002", "date": "2026-06-05", "time": "12:34", "speaker": "Zy",
     "raw_quote": "拉群为了给你装逼嘛[翻白眼]",
     "context": "Tf 建议拉群",
     "claim_tags": ["expression-nonliteral"],
     "confidence": "high", "counter_evidence": None,
     "alternative_explanation": "可能只是开玩笑的社交表达",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},

    # 从 v3 报告保留的关键证据
    {"evidence_id": "E-20260517-001", "date": "2026-05-17", "time": "03:09", "speaker": "Tf",
     "raw_quote": "保持低调感别说话",
     "context": "Zy 表白后 Tf 的回应",
     "claim_tags": ["attachment-avoidant", "boundary-implicit"],
     "confidence": "high", "counter_evidence": "可能是当前阶段不想公开",
     "alternative_explanation": "可能只是谨慎，而非回避",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20260528-001", "date": "2026-05-28", "time": "01:22", "speaker": "Zy",
     "raw_quote": "师姐出去没找到师兄",
     "context": "答辩后疏离期开始",
     "claim_tags": ["turning-point"],
     "confidence": "medium", "counter_evidence": None,
     "alternative_explanation": "可能只是正常的实验室信息传递",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
    {"evidence_id": "E-20241101-001", "date": "2024-11-01", "time": None, "speaker": "Tf",
     "raw_quote": "我在恐惧害怕的玩",
     "context": "早期 Tf 表达焦虑",
     "claim_tags": ["attachment-anxious", "expression-emotional"],
     "confidence": "medium", "counter_evidence": None,
     "alternative_explanation": "可能只是随口一说",
     "source_file": "conversations/0001/messages.json",
     "analysis_version": "0.9.0"},
]


def main():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        for ev in EVIDENCE:
            f.write(json.dumps(ev, ensure_ascii=False) + "\n")
    print(f"Wrote {len(EVIDENCE)} evidence records to {OUTPUT}")


if __name__ == "__main__":
    main()
